$axure.loadCurrentPage({
  "url":"关于我们.html",
  "generationDate":new Date(1456905180723.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"627432d4e4074ba6a1f8cb20407993ff",
    "type":"Axure:Page",
    "name":"关于我们",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5702a3cdf5164df0bbc43fb0eeaf00e1",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":20},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"66109d481886474e9514bbf33128bc82",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6f49cd178d7e425797325376932238b5",
                  "label":"",
                  "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":810,
                      "height":530}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"26ab4ed6237c42bcaba97eef46e73043",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":810,
                          "height":530}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u1.png"}},
{
                  "id":"6fde07c2ab6b4a66a32f889a57410e5a",
                  "label":"",
                  "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":810,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7da3a07ebe5943379395700c1ba669c2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":810,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"a49b52ec87ae4508bf5016e5bc48c798",
                  "label":"",
                  "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":5},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"827569ac03fd40b2801684c47fdf2a16",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":5},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u5.png"}},
{
                  "id":"d66e4ae04d9f4ae3ae4e7d2141547fa9",
                  "label":"",
                  "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":550,
                      "y":30},
                    "size":{
                      "width":30,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"56a11a72cf764d758a16a9fd6db4f0d0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":550,
                          "y":30},
                        "size":{
                          "width":30,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f1bb6a4e36d1436ab4943e10bde8d6ec",
                  "label":"",
                  "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":627,
                      "y":31},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f43fbd2ec2174ce091a97fa1f5436aaa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":627,
                          "y":31},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 文档",
                              "target":{
                                "targetType":"page",
                                "url":"文档.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"752734e4cc8647129867040f19eca6ad",
                  "label":"",
                  "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":701,
                      "y":31},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b1b97f3444634713aba65acefc1d40ee",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":701,
                          "y":31},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 关于我们",
                              "target":{
                                "targetType":"page",
                                "url":"关于我们.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"cc26f19e869f40dabf5bded3cfd37fbb",
                  "label":"",
                  "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":590,
                      "y":31},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cf901f0283414959bf5e14496d78e785",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":590,
                          "y":31},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 技术",
                              "target":{
                                "targetType":"page",
                                "url":"技术.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"15b7384a43e44db88588614fbead208a",
                  "label":"",
                  "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":490},
                    "size":{
                      "width":810,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b44d1510e8e24feb928c6ef5babf30cf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":490},
                        "size":{
                          "width":810,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u15.png"}},
{
                  "id":"d591742097a34c7788493031a04aaaa6",
                  "label":"",
                  "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":88,
                      "y":502},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3d8ffd588ad547668855efc78264592f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":88,
                          "y":502},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d82fafcbfdb14fb898e9541e267236aa",
                  "label":"",
                  "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":140,
                      "y":502},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"45d19b00c450491ea57ae142eecbb206",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":140,
                          "y":502},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2f16da0620574d05b91ce1cb633cef3b",
                  "label":"",
                  "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":216,
                      "y":502},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cd0ddd311a7b467eacaa4e962aef3bcb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":216,
                          "y":502},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1e2455ef1cbd41379c55e65835317b67",
                  "label":"",
                  "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":39,
                      "y":502},
                    "size":{
                      "width":29,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fc92a61e701744118eb766b1dbd62414",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":39,
                          "y":502},
                        "size":{
                          "width":29,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6fb573a19d804c728629c4374e5cd97f",
                  "label":"",
                  "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":279,
                      "y":502},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e3b404e2a9ad43b489a585bebb5a3dc5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":279,
                          "y":502},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8cfdf49a2a3b4c6e94bd8f84779a389d",
                  "label":"",
                  "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":664,
                      "y":31},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"db9866c80c8841d3b768ad4fc7d2d31c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":664,
                          "y":31},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 文档",
                              "target":{
                                "targetType":"page",
                                "url":"文档.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3eb039f2d21447bf9e61ea77d3225b07",
                  "label":"",
                  "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":764,
                      "y":28},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"43a82c1d1d914641aeb46d266b6027d8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5702a3cdf5164df0bbc43fb0eeaf00e1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":764,
                          "y":28},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u36.png"}}]}]},
{
          "id":"75ada1bc75d141b0b94567934c891582",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":215},
            "size":{
              "width":810,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9095b262f3a9481287774a8d987298e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":215},
                "size":{
                  "width":810,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于我们/u31.png"}},
{
          "id":"7e4bdfad6a464b84b2e9591677c4f22f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":370},
            "size":{
              "width":810,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c14198e82eb040a788ba0d9f34f32de2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":370},
                "size":{
                  "width":810,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于我们/u33.png"}},
{
          "id":"dd852cbf35cb4189a03e4f47d51b876c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":70,
              "y":218},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17bf4f37d65a4b84832c608ef1fe9390",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":70,
                  "y":218},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6aa109d06117467a9935ffd6d1d0efae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":255},
            "size":{
              "width":295,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b85f8d6340445f69243be4b82f2cd52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":255},
                "size":{
                  "width":295,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee2f2dd16e5344bcb111f29bcc725983",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":325},
            "size":{
              "width":178,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0da56efcd4804be690debed12fe35193",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":325},
                "size":{
                  "width":178,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85946f1a580a4b20a8862908e92295b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":412,
              "y":289},
            "size":{
              "width":138,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"951d4e7c542e412c9b575961647e68ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":412,
                  "y":289},
                "size":{
                  "width":138,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13482396ad844317b561000f28a8eff2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":404,
              "y":255},
            "size":{
              "width":216,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82cf453b1d584c6a92e151eaa81bd593",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":404,
                  "y":255},
                "size":{
                  "width":216,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5eb488096cc44fd4b770b1c3f66b8f47",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":70,
              "y":383},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e7e23edc689482392e5fa675ca2304e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":70,
                  "y":383},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bfff2315058b4cc4b64b3d0db7b348b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":415},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed13aa9ac3164dc994ad40789250e651",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":415},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5e032ceff394846b4eb94b49f04de3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":441},
            "size":{
              "width":115,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d98072d3bf1e40929c1b45533aa4f61f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":441},
                "size":{
                  "width":115,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"245c3010048c414bad6762a711b35c0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":467},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47eb4d12c54e41e9979f312021952967",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":467},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1642e392bfdd4bccb972d1ee1863f3cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":289},
            "size":{
              "width":180,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f025cdd45194e85bf059bb907746327",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":289},
                "size":{
                  "width":180,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3605240005b4508b767794af54f176f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":95},
            "size":{
              "width":810,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0877358ad47d45179faa2aba12b8be78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":95},
                "size":{
                  "width":810,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技术/u31.png"}},
{
          "id":"1afae154ebe14b2c8319f95ca1e9de3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":70,
              "y":110},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5b05ad540fd40528d3e209b0b564252",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":70,
                  "y":110},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e744075454f4f5fa9bf0b5c308dbb65",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":110},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"622db1718bab43ea9f36cb51e4edfa72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":110},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于我们/u59.png"}},
{
          "id":"dfa0d66a2ed544e781a9f9477ccb4f15",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":110},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f64d2498a0d945f6a6b89ae603362adb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":110},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于我们/u59.png"}},
{
          "id":"8d96d01a4d8e4815a2e1e0359ac23f34",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":396,
              "y":110},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95fc15e1e517469bb67e3e1ef3511f7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":396,
                  "y":110},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于我们/u59.png"}},
{
          "id":"166bc1d15d8f428ebe9ffc7a2155073b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":110},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bae49b53628842979d87795d4789e731",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":110},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于我们/u59.png"}},
{
          "id":"8f47d8f79ec54855b1c9c7b1f6f18b1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":110},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07817b1d54c241ed8e53af75f29630b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":110},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于我们/u59.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "5702a3cdf5164df0bbc43fb0eeaf00e1":{
      "scriptId":"u0"},
    "6f49cd178d7e425797325376932238b5":{
      "scriptId":"u1"},
    "26ab4ed6237c42bcaba97eef46e73043":{
      "scriptId":"u2"},
    "6fde07c2ab6b4a66a32f889a57410e5a":{
      "scriptId":"u3"},
    "7da3a07ebe5943379395700c1ba669c2":{
      "scriptId":"u4"},
    "a49b52ec87ae4508bf5016e5bc48c798":{
      "scriptId":"u5"},
    "827569ac03fd40b2801684c47fdf2a16":{
      "scriptId":"u6"},
    "d66e4ae04d9f4ae3ae4e7d2141547fa9":{
      "scriptId":"u7"},
    "56a11a72cf764d758a16a9fd6db4f0d0":{
      "scriptId":"u8"},
    "f1bb6a4e36d1436ab4943e10bde8d6ec":{
      "scriptId":"u9"},
    "f43fbd2ec2174ce091a97fa1f5436aaa":{
      "scriptId":"u10"},
    "752734e4cc8647129867040f19eca6ad":{
      "scriptId":"u11"},
    "b1b97f3444634713aba65acefc1d40ee":{
      "scriptId":"u12"},
    "cc26f19e869f40dabf5bded3cfd37fbb":{
      "scriptId":"u13"},
    "cf901f0283414959bf5e14496d78e785":{
      "scriptId":"u14"},
    "15b7384a43e44db88588614fbead208a":{
      "scriptId":"u15"},
    "b44d1510e8e24feb928c6ef5babf30cf":{
      "scriptId":"u16"},
    "d591742097a34c7788493031a04aaaa6":{
      "scriptId":"u17"},
    "3d8ffd588ad547668855efc78264592f":{
      "scriptId":"u18"},
    "d82fafcbfdb14fb898e9541e267236aa":{
      "scriptId":"u19"},
    "45d19b00c450491ea57ae142eecbb206":{
      "scriptId":"u20"},
    "2f16da0620574d05b91ce1cb633cef3b":{
      "scriptId":"u21"},
    "cd0ddd311a7b467eacaa4e962aef3bcb":{
      "scriptId":"u22"},
    "1e2455ef1cbd41379c55e65835317b67":{
      "scriptId":"u23"},
    "fc92a61e701744118eb766b1dbd62414":{
      "scriptId":"u24"},
    "6fb573a19d804c728629c4374e5cd97f":{
      "scriptId":"u25"},
    "e3b404e2a9ad43b489a585bebb5a3dc5":{
      "scriptId":"u26"},
    "8cfdf49a2a3b4c6e94bd8f84779a389d":{
      "scriptId":"u27"},
    "db9866c80c8841d3b768ad4fc7d2d31c":{
      "scriptId":"u28"},
    "3eb039f2d21447bf9e61ea77d3225b07":{
      "scriptId":"u29"},
    "43a82c1d1d914641aeb46d266b6027d8":{
      "scriptId":"u30"},
    "75ada1bc75d141b0b94567934c891582":{
      "scriptId":"u31"},
    "9095b262f3a9481287774a8d987298e0":{
      "scriptId":"u32"},
    "7e4bdfad6a464b84b2e9591677c4f22f":{
      "scriptId":"u33"},
    "c14198e82eb040a788ba0d9f34f32de2":{
      "scriptId":"u34"},
    "dd852cbf35cb4189a03e4f47d51b876c":{
      "scriptId":"u35"},
    "17bf4f37d65a4b84832c608ef1fe9390":{
      "scriptId":"u36"},
    "6aa109d06117467a9935ffd6d1d0efae":{
      "scriptId":"u37"},
    "7b85f8d6340445f69243be4b82f2cd52":{
      "scriptId":"u38"},
    "ee2f2dd16e5344bcb111f29bcc725983":{
      "scriptId":"u39"},
    "0da56efcd4804be690debed12fe35193":{
      "scriptId":"u40"},
    "85946f1a580a4b20a8862908e92295b9":{
      "scriptId":"u41"},
    "951d4e7c542e412c9b575961647e68ff":{
      "scriptId":"u42"},
    "13482396ad844317b561000f28a8eff2":{
      "scriptId":"u43"},
    "82cf453b1d584c6a92e151eaa81bd593":{
      "scriptId":"u44"},
    "5eb488096cc44fd4b770b1c3f66b8f47":{
      "scriptId":"u45"},
    "3e7e23edc689482392e5fa675ca2304e":{
      "scriptId":"u46"},
    "bfff2315058b4cc4b64b3d0db7b348b5":{
      "scriptId":"u47"},
    "ed13aa9ac3164dc994ad40789250e651":{
      "scriptId":"u48"},
    "b5e032ceff394846b4eb94b49f04de3c":{
      "scriptId":"u49"},
    "d98072d3bf1e40929c1b45533aa4f61f":{
      "scriptId":"u50"},
    "245c3010048c414bad6762a711b35c0f":{
      "scriptId":"u51"},
    "47eb4d12c54e41e9979f312021952967":{
      "scriptId":"u52"},
    "1642e392bfdd4bccb972d1ee1863f3cc":{
      "scriptId":"u53"},
    "3f025cdd45194e85bf059bb907746327":{
      "scriptId":"u54"},
    "d3605240005b4508b767794af54f176f":{
      "scriptId":"u55"},
    "0877358ad47d45179faa2aba12b8be78":{
      "scriptId":"u56"},
    "1afae154ebe14b2c8319f95ca1e9de3e":{
      "scriptId":"u57"},
    "f5b05ad540fd40528d3e209b0b564252":{
      "scriptId":"u58"},
    "3e744075454f4f5fa9bf0b5c308dbb65":{
      "scriptId":"u59"},
    "622db1718bab43ea9f36cb51e4edfa72":{
      "scriptId":"u60"},
    "dfa0d66a2ed544e781a9f9477ccb4f15":{
      "scriptId":"u61"},
    "f64d2498a0d945f6a6b89ae603362adb":{
      "scriptId":"u62"},
    "8d96d01a4d8e4815a2e1e0359ac23f34":{
      "scriptId":"u63"},
    "95fc15e1e517469bb67e3e1ef3511f7f":{
      "scriptId":"u64"},
    "166bc1d15d8f428ebe9ffc7a2155073b":{
      "scriptId":"u65"},
    "bae49b53628842979d87795d4789e731":{
      "scriptId":"u66"},
    "8f47d8f79ec54855b1c9c7b1f6f18b1a":{
      "scriptId":"u67"},
    "07817b1d54c241ed8e53af75f29630b9":{
      "scriptId":"u68"}}});