$axure.loadCurrentPage({
  "url":"技术.html",
  "generationDate":new Date(1456905180483.57),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"31d5c022dfa84370a37dfba79bb1aada",
    "type":"Axure:Page",
    "name":"技术",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"511cf4e1dbe641caa4666bbba5fba91f",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":20},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"f88febea3aac45049cba1ec375416f18",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f1a1b68fee9e414c85cf54b6baf6355f",
                  "label":"",
                  "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":810,
                      "height":530}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ea37799e14e04b4498964ce5b6d9f207",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":810,
                          "height":530}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u1.png"}},
{
                  "id":"926e5b3ac71b4307a56d09767ab45870",
                  "label":"",
                  "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":810,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"33752448b45941d3a6d077877d713837",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":810,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"a979b2d6a12147218486d863661745f3",
                  "label":"",
                  "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":5},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2c4e6814b8c2428494f153f81ee1927c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":5},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u5.png"}},
{
                  "id":"70eee0071f2042b1a7d310195d26f3a4",
                  "label":"",
                  "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":550,
                      "y":30},
                    "size":{
                      "width":30,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b24ba45900474e7eadbf268d012e5aa6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":550,
                          "y":30},
                        "size":{
                          "width":30,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c5b132660fdc40ea81577bbb0ce0dd4b",
                  "label":"",
                  "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":627,
                      "y":31},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"34f5191df73a4575988639d4bc8be42e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":627,
                          "y":31},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 文档",
                              "target":{
                                "targetType":"page",
                                "url":"文档.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b8a104869c2946ea888aadf2ec1a71f7",
                  "label":"",
                  "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":701,
                      "y":31},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8e0b747e39e3486c937267e414a8cfff",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":701,
                          "y":31},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 关于我们",
                              "target":{
                                "targetType":"page",
                                "url":"关于我们.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0cfb3432fb3d40a7a4074bd804442d11",
                  "label":"",
                  "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":590,
                      "y":31},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"82b399fd79204b17b2eaf22d24e091b9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":590,
                          "y":31},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 技术",
                              "target":{
                                "targetType":"page",
                                "url":"技术.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ea480ffd09634a1f84dc19d042b4117e",
                  "label":"",
                  "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":490},
                    "size":{
                      "width":810,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6ad3197d226e412da0ba6afdfd7fa069",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":490},
                        "size":{
                          "width":810,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u15.png"}},
{
                  "id":"d55848f1980048d7b7303ce8acce0afc",
                  "label":"",
                  "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":88,
                      "y":502},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"44ee919d65864e7e976c23d5cd010642",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":88,
                          "y":502},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b5b8af62065d46398f77458c069d4276",
                  "label":"",
                  "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":140,
                      "y":502},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c3c2a463a6544f52bec17d8adc77f15b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":140,
                          "y":502},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a723fe2e18b546c4a06bc4a6812d8f1f",
                  "label":"",
                  "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":216,
                      "y":502},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4a6b000c7399490bba7562b67faa7d5d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":216,
                          "y":502},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"af85148903eb4d76bc1bec2c2e035cbb",
                  "label":"",
                  "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":39,
                      "y":502},
                    "size":{
                      "width":29,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"20ededf7aaa84c5595a08e70e284d501",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":39,
                          "y":502},
                        "size":{
                          "width":29,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"cd9940507d88465095a536aae270eebf",
                  "label":"",
                  "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":279,
                      "y":502},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ee698668bcc743548b52458abb00bb16",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":279,
                          "y":502},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"359a4329573f49bba918102a44ce2e0e",
                  "label":"",
                  "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":664,
                      "y":31},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"225ccbc960354168a6b0d62eb34315d3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":664,
                          "y":31},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 文档",
                              "target":{
                                "targetType":"page",
                                "url":"文档.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d2eb088ba57d4bcb9b09bfc0742aafa3",
                  "label":"",
                  "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":764,
                      "y":28},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0411cf549cc7430197b6a34a6585a7d9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"511cf4e1dbe641caa4666bbba5fba91f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":764,
                          "y":28},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u36.png"}}]}]},
{
          "id":"19d15253f4ce4c3d9dd064701976e9af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":270},
            "size":{
              "width":810,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed071c7d2d1642f780dafc35d1ab1019",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":270},
                "size":{
                  "width":810,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技术/u31.png"}},
{
          "id":"dc1f45eb4cfa45e08813d9d143292341",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":390},
            "size":{
              "width":810,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0130346210324738936e9dc85f729899",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":390},
                "size":{
                  "width":810,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技术/u31.png"}},
{
          "id":"da8da013c8094dcb9ac848a53db899c6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":295},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfce122a080a4a05bc97b073f4bca306",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":295},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u5.png"}},
{
          "id":"48db9188d37043ff9dcf911351e67055",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":415},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e79e273d7aa547d7ae0eb318db91940a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":415},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u5.png"}},
{
          "id":"1e212e58be4b4cd48b8ee9e690a21b9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":127,
              "y":281},
            "size":{
              "width":652,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17611f1e00c746d2a4ad990c8d305c22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":127,
                  "y":281},
                "size":{
                  "width":652,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29561c9ec0784d04a2d7563bd2a03274",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":127,
              "y":403},
            "size":{
              "width":652,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea5cf2f9f0d84be5bd16a83ebd38e81d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":127,
                  "y":403},
                "size":{
                  "width":652,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2de1869ed15c42c5b7440333cb163733",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":830,
              "y":130},
            "size":{
              "width":200,
              "height":100},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2d3e2d7e1cc48d4a22dc3e8c5728891",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":830,
                  "y":130},
                "size":{
                  "width":200,
                  "height":100},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技术/u43.png"}},
{
          "id":"846c92be594249bea10d54f249a3c51f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":29,
              "y":98},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96efcd4458cf49fc9611907cbdd70fc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":29,
                  "y":98},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee7716b6422d40a58eae1faeda1dc71e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":122},
            "size":{
              "width":810,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a691a56f34b40bba22024892bf3623a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":122},
                "size":{
                  "width":810,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技术/u47.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "511cf4e1dbe641caa4666bbba5fba91f":{
      "scriptId":"u0"},
    "f1a1b68fee9e414c85cf54b6baf6355f":{
      "scriptId":"u1"},
    "ea37799e14e04b4498964ce5b6d9f207":{
      "scriptId":"u2"},
    "926e5b3ac71b4307a56d09767ab45870":{
      "scriptId":"u3"},
    "33752448b45941d3a6d077877d713837":{
      "scriptId":"u4"},
    "a979b2d6a12147218486d863661745f3":{
      "scriptId":"u5"},
    "2c4e6814b8c2428494f153f81ee1927c":{
      "scriptId":"u6"},
    "70eee0071f2042b1a7d310195d26f3a4":{
      "scriptId":"u7"},
    "b24ba45900474e7eadbf268d012e5aa6":{
      "scriptId":"u8"},
    "c5b132660fdc40ea81577bbb0ce0dd4b":{
      "scriptId":"u9"},
    "34f5191df73a4575988639d4bc8be42e":{
      "scriptId":"u10"},
    "b8a104869c2946ea888aadf2ec1a71f7":{
      "scriptId":"u11"},
    "8e0b747e39e3486c937267e414a8cfff":{
      "scriptId":"u12"},
    "0cfb3432fb3d40a7a4074bd804442d11":{
      "scriptId":"u13"},
    "82b399fd79204b17b2eaf22d24e091b9":{
      "scriptId":"u14"},
    "ea480ffd09634a1f84dc19d042b4117e":{
      "scriptId":"u15"},
    "6ad3197d226e412da0ba6afdfd7fa069":{
      "scriptId":"u16"},
    "d55848f1980048d7b7303ce8acce0afc":{
      "scriptId":"u17"},
    "44ee919d65864e7e976c23d5cd010642":{
      "scriptId":"u18"},
    "b5b8af62065d46398f77458c069d4276":{
      "scriptId":"u19"},
    "c3c2a463a6544f52bec17d8adc77f15b":{
      "scriptId":"u20"},
    "a723fe2e18b546c4a06bc4a6812d8f1f":{
      "scriptId":"u21"},
    "4a6b000c7399490bba7562b67faa7d5d":{
      "scriptId":"u22"},
    "af85148903eb4d76bc1bec2c2e035cbb":{
      "scriptId":"u23"},
    "20ededf7aaa84c5595a08e70e284d501":{
      "scriptId":"u24"},
    "cd9940507d88465095a536aae270eebf":{
      "scriptId":"u25"},
    "ee698668bcc743548b52458abb00bb16":{
      "scriptId":"u26"},
    "359a4329573f49bba918102a44ce2e0e":{
      "scriptId":"u27"},
    "225ccbc960354168a6b0d62eb34315d3":{
      "scriptId":"u28"},
    "d2eb088ba57d4bcb9b09bfc0742aafa3":{
      "scriptId":"u29"},
    "0411cf549cc7430197b6a34a6585a7d9":{
      "scriptId":"u30"},
    "19d15253f4ce4c3d9dd064701976e9af":{
      "scriptId":"u31"},
    "ed071c7d2d1642f780dafc35d1ab1019":{
      "scriptId":"u32"},
    "dc1f45eb4cfa45e08813d9d143292341":{
      "scriptId":"u33"},
    "0130346210324738936e9dc85f729899":{
      "scriptId":"u34"},
    "da8da013c8094dcb9ac848a53db899c6":{
      "scriptId":"u35"},
    "bfce122a080a4a05bc97b073f4bca306":{
      "scriptId":"u36"},
    "48db9188d37043ff9dcf911351e67055":{
      "scriptId":"u37"},
    "e79e273d7aa547d7ae0eb318db91940a":{
      "scriptId":"u38"},
    "1e212e58be4b4cd48b8ee9e690a21b9c":{
      "scriptId":"u39"},
    "17611f1e00c746d2a4ad990c8d305c22":{
      "scriptId":"u40"},
    "29561c9ec0784d04a2d7563bd2a03274":{
      "scriptId":"u41"},
    "ea5cf2f9f0d84be5bd16a83ebd38e81d":{
      "scriptId":"u42"},
    "2de1869ed15c42c5b7440333cb163733":{
      "scriptId":"u43"},
    "f2d3e2d7e1cc48d4a22dc3e8c5728891":{
      "scriptId":"u44"},
    "846c92be594249bea10d54f249a3c51f":{
      "scriptId":"u45"},
    "96efcd4458cf49fc9611907cbdd70fc9":{
      "scriptId":"u46"},
    "ee7716b6422d40a58eae1faeda1dc71e":{
      "scriptId":"u47"},
    "0a691a56f34b40bba22024892bf3623a":{
      "scriptId":"u48"}}});