$axure.loadCurrentPage({
  "url":"下载页.html",
  "generationDate":new Date(1457071974618.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d76957734e6f4002851bda958b5d10e1",
    "type":"Axure:Page",
    "name":"下载页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5ac80dc4ef984c3b8f5d3948df0cdc39",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":20},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"213d4addccf048199ff406a0027bca0d",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e8eff81535f241d9b339a28b20b4a74a",
                  "label":"",
                  "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":810,
                      "height":530}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"79fc45f0adf74a67b47ec63a1c613bec",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":810,
                          "height":530}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/下载页/u1.png"}},
{
                  "id":"87a7ee234d8c49ebb4adcba164788a2e",
                  "label":"",
                  "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":810,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b600f43fec0749c6ac68d5d1d2424731",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":810,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"a157a8996eef4fdfb553efa9d6d8346d",
                  "label":"",
                  "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":5},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ef786a14dc4e4563ad5eb7cf8177c6f3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":5},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u5.png"}},
{
                  "id":"d8bb54138c7f401890974042b2e27f25",
                  "label":"",
                  "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":550,
                      "y":30},
                    "size":{
                      "width":30,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7446d0bdcc08426a909a613bb4ef8ca0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":550,
                          "y":30},
                        "size":{
                          "width":30,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"99945d91ab3848468f738074429df278",
                  "label":"",
                  "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":627,
                      "y":31},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2e8f5aca994f4a16a40c236570f05832",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":627,
                          "y":31},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 文档",
                              "target":{
                                "targetType":"page",
                                "url":"文档.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"60eda74f19e140feb73e55b812339938",
                  "label":"",
                  "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":701,
                      "y":31},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"892c13bcd5aa4d27993739ef4a99c93f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":701,
                          "y":31},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 链接",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1e4a2710860f494c865704f1648e0a92",
                  "label":"",
                  "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":590,
                      "y":31},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ce41c2d8b46c44f783f3bc92f499f6d2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":590,
                          "y":31},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 链接",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9c980abb49eb46098c925f901d5bf654",
                  "label":"",
                  "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":490},
                    "size":{
                      "width":810,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b5df97bb3eb34462ab4dd24029b580cc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":490},
                        "size":{
                          "width":810,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u136.png"}},
{
                  "id":"961f4add41724bb4b299a8989f15982a",
                  "label":"",
                  "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":88,
                      "y":502},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bd3791f482614802ae30c430407904df",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":88,
                          "y":502},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2b48b5fdff8346efb252f15f60e556ab",
                  "label":"",
                  "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":140,
                      "y":502},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c54422779a1c449d8dce8257747f13ba",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":140,
                          "y":502},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"73392d0b680b438f9c9dffda84a902db",
                  "label":"",
                  "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":216,
                      "y":502},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"478d4fa21a334ae0b2f1af562a0f70b3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":216,
                          "y":502},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1c6c7584e75747779239f6559e199a71",
                  "label":"",
                  "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":39,
                      "y":502},
                    "size":{
                      "width":29,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"113f1066b9b649afbe29c706800d4098",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":39,
                          "y":502},
                        "size":{
                          "width":29,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8a5a6d5cb0814fee933e713257c01602",
                  "label":"",
                  "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":279,
                      "y":502},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fc8a132f43b24e8281ceaef00ec137be",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":279,
                          "y":502},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5da91f8e97ea4c05bc15348e3fa6e295",
                  "label":"",
                  "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":664,
                      "y":31},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"668226e007b14fe4a565499dd3e558c6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":664,
                          "y":31},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 文档",
                              "target":{
                                "targetType":"page",
                                "url":"文档.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e0f4ed6286e34b4a8f6d98403ed1ff12",
                  "label":"",
                  "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":764,
                      "y":28},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"736a17ef32d74d34a062f5ff8cc8fb8a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5ac80dc4ef984c3b8f5d3948df0cdc39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":764,
                          "y":28},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u22.png"}}]}]},
{
          "id":"bfdfacf1a90f42f5bedcfa9e6aba219c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":32,
              "y":100},
            "size":{
              "width":41,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b48c8570d151410d9212228fc2a1188c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":32,
                  "y":100},
                "size":{
                  "width":41,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25bc3cd192dc4ff1ba96e77c39f463f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":132},
            "size":{
              "width":748,
              "height":164}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66e6d11a3c0f4ec586513e7d5a87cce6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":132},
                "size":{
                  "width":748,
                  "height":164}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/下载页/u33.png"}},
{
          "id":"f785b9b107664223bf0e432690fc5e65",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":32,
              "y":306},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8341850aa0e5474da9a3674b202c75bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":32,
                  "y":306},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ad961066d604205820677ed6da5ef6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":337},
            "size":{
              "width":748,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9b55b8a9c6948cfa76996f832e42568",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":337},
                "size":{
                  "width":748,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/下载页/u37.png"}},
{
          "id":"461f4562e900436580ce061e3fae1739",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":32,
              "y":415},
            "size":{
              "width":41,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e11a1fa732a943619fc6dc95351865cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":32,
                  "y":415},
                "size":{
                  "width":41,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9236def77804a1b8acf01342fde2e5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":444},
            "size":{
              "width":748,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0f68d5abf6a441a8e535a4c189ef06f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":444},
                "size":{
                  "width":748,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/下载页/u37.png"}},
{
          "id":"55b9e60a15924dd0a70e5ed4ac65fb7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0033CC,
              "opacity":1},
            "location":{
              "x":41,
              "y":141},
            "size":{
              "width":97,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc03b4470fea4957975ff8a64f9a0f56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033CC,
                  "opacity":1},
                "location":{
                  "x":41,
                  "y":141},
                "size":{
                  "width":97,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa605db249c1444e99430ab2d8defec1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0033CC,
              "opacity":1},
            "location":{
              "x":41,
              "y":196},
            "size":{
              "width":97,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce417f7b77324a629d628b0a6de9d5d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033CC,
                  "opacity":1},
                "location":{
                  "x":41,
                  "y":196},
                "size":{
                  "width":97,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2bd3a9e2c95140b29b8a43eb30a9bd44",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0033CC,
              "opacity":1},
            "location":{
              "x":41,
              "y":247},
            "size":{
              "width":64,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ddc12521a0d4c439e76ec9e2165d4f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033CC,
                  "opacity":1},
                "location":{
                  "x":41,
                  "y":247},
                "size":{
                  "width":64,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59145a4432a2407fbb98d36ceab3fbc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":158},
            "size":{
              "width":325,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52c97cd02af5469ca4ae9859620b1b29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":158},
                "size":{
                  "width":325,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3857431c794044b3ac5584778d533b24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":212},
            "size":{
              "width":325,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"517d65d412aa42b2b263c4ef4809e953",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":212},
                "size":{
                  "width":325,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6aa48b359594a25a7b1f6474801520d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":261},
            "size":{
              "width":325,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d12aae24e5842b8b75d997533ea8480",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":261},
                "size":{
                  "width":325,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"042a910171614fc3afb70e4239d63410",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":344},
            "size":{
              "width":276,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f44f90bd45e4a8c98ec8b164a75c67f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":344},
                "size":{
                  "width":276,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45c166ea07d54c50a17dc20b25b66261",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":362},
            "size":{
              "width":327,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e4942cb6a0f4c4f91d785bd59e06c97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":362},
                "size":{
                  "width":327,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b00048b3ae364f84b2320bfb8c3a88f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0033CC,
              "opacity":1},
            "location":{
              "x":41,
              "y":449},
            "size":{
              "width":127,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5eba2554a144d0c8d2d3f3d65c25b5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033CC,
                  "opacity":1},
                "location":{
                  "x":41,
                  "y":449},
                "size":{
                  "width":127,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a37ef8781f9741daad96e43b1470c59d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":467},
            "size":{
              "width":325,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fa397f6443e4d9798fdb006cb59f203",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":467},
                "size":{
                  "width":325,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4d12eff69ee47a484bd933422c538c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":108},
            "size":{
              "width":97,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2f271fd8c554569b2a7a6c4d19c7030",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":108},
                "size":{
                  "width":97,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efbec744081a4c88bbd76cacc94c48d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":830,
              "y":141},
            "size":{
              "width":200,
              "height":100},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99ebc89ede9e45fc98a61550d97f3675",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":830,
                  "y":141},
                "size":{
                  "width":200,
                  "height":100},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u148.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "5ac80dc4ef984c3b8f5d3948df0cdc39":{
      "scriptId":"u0"},
    "e8eff81535f241d9b339a28b20b4a74a":{
      "scriptId":"u1"},
    "79fc45f0adf74a67b47ec63a1c613bec":{
      "scriptId":"u2"},
    "87a7ee234d8c49ebb4adcba164788a2e":{
      "scriptId":"u3"},
    "b600f43fec0749c6ac68d5d1d2424731":{
      "scriptId":"u4"},
    "a157a8996eef4fdfb553efa9d6d8346d":{
      "scriptId":"u5"},
    "ef786a14dc4e4563ad5eb7cf8177c6f3":{
      "scriptId":"u6"},
    "d8bb54138c7f401890974042b2e27f25":{
      "scriptId":"u7"},
    "7446d0bdcc08426a909a613bb4ef8ca0":{
      "scriptId":"u8"},
    "99945d91ab3848468f738074429df278":{
      "scriptId":"u9"},
    "2e8f5aca994f4a16a40c236570f05832":{
      "scriptId":"u10"},
    "60eda74f19e140feb73e55b812339938":{
      "scriptId":"u11"},
    "892c13bcd5aa4d27993739ef4a99c93f":{
      "scriptId":"u12"},
    "1e4a2710860f494c865704f1648e0a92":{
      "scriptId":"u13"},
    "ce41c2d8b46c44f783f3bc92f499f6d2":{
      "scriptId":"u14"},
    "9c980abb49eb46098c925f901d5bf654":{
      "scriptId":"u15"},
    "b5df97bb3eb34462ab4dd24029b580cc":{
      "scriptId":"u16"},
    "961f4add41724bb4b299a8989f15982a":{
      "scriptId":"u17"},
    "bd3791f482614802ae30c430407904df":{
      "scriptId":"u18"},
    "2b48b5fdff8346efb252f15f60e556ab":{
      "scriptId":"u19"},
    "c54422779a1c449d8dce8257747f13ba":{
      "scriptId":"u20"},
    "73392d0b680b438f9c9dffda84a902db":{
      "scriptId":"u21"},
    "478d4fa21a334ae0b2f1af562a0f70b3":{
      "scriptId":"u22"},
    "1c6c7584e75747779239f6559e199a71":{
      "scriptId":"u23"},
    "113f1066b9b649afbe29c706800d4098":{
      "scriptId":"u24"},
    "8a5a6d5cb0814fee933e713257c01602":{
      "scriptId":"u25"},
    "fc8a132f43b24e8281ceaef00ec137be":{
      "scriptId":"u26"},
    "5da91f8e97ea4c05bc15348e3fa6e295":{
      "scriptId":"u27"},
    "668226e007b14fe4a565499dd3e558c6":{
      "scriptId":"u28"},
    "e0f4ed6286e34b4a8f6d98403ed1ff12":{
      "scriptId":"u29"},
    "736a17ef32d74d34a062f5ff8cc8fb8a":{
      "scriptId":"u30"},
    "bfdfacf1a90f42f5bedcfa9e6aba219c":{
      "scriptId":"u31"},
    "b48c8570d151410d9212228fc2a1188c":{
      "scriptId":"u32"},
    "25bc3cd192dc4ff1ba96e77c39f463f8":{
      "scriptId":"u33"},
    "66e6d11a3c0f4ec586513e7d5a87cce6":{
      "scriptId":"u34"},
    "f785b9b107664223bf0e432690fc5e65":{
      "scriptId":"u35"},
    "8341850aa0e5474da9a3674b202c75bc":{
      "scriptId":"u36"},
    "3ad961066d604205820677ed6da5ef6b":{
      "scriptId":"u37"},
    "e9b55b8a9c6948cfa76996f832e42568":{
      "scriptId":"u38"},
    "461f4562e900436580ce061e3fae1739":{
      "scriptId":"u39"},
    "e11a1fa732a943619fc6dc95351865cb":{
      "scriptId":"u40"},
    "d9236def77804a1b8acf01342fde2e5d":{
      "scriptId":"u41"},
    "c0f68d5abf6a441a8e535a4c189ef06f":{
      "scriptId":"u42"},
    "55b9e60a15924dd0a70e5ed4ac65fb7e":{
      "scriptId":"u43"},
    "dc03b4470fea4957975ff8a64f9a0f56":{
      "scriptId":"u44"},
    "aa605db249c1444e99430ab2d8defec1":{
      "scriptId":"u45"},
    "ce417f7b77324a629d628b0a6de9d5d4":{
      "scriptId":"u46"},
    "2bd3a9e2c95140b29b8a43eb30a9bd44":{
      "scriptId":"u47"},
    "5ddc12521a0d4c439e76ec9e2165d4f8":{
      "scriptId":"u48"},
    "59145a4432a2407fbb98d36ceab3fbc1":{
      "scriptId":"u49"},
    "52c97cd02af5469ca4ae9859620b1b29":{
      "scriptId":"u50"},
    "3857431c794044b3ac5584778d533b24":{
      "scriptId":"u51"},
    "517d65d412aa42b2b263c4ef4809e953":{
      "scriptId":"u52"},
    "f6aa48b359594a25a7b1f6474801520d":{
      "scriptId":"u53"},
    "3d12aae24e5842b8b75d997533ea8480":{
      "scriptId":"u54"},
    "042a910171614fc3afb70e4239d63410":{
      "scriptId":"u55"},
    "6f44f90bd45e4a8c98ec8b164a75c67f":{
      "scriptId":"u56"},
    "45c166ea07d54c50a17dc20b25b66261":{
      "scriptId":"u57"},
    "1e4942cb6a0f4c4f91d785bd59e06c97":{
      "scriptId":"u58"},
    "b00048b3ae364f84b2320bfb8c3a88f0":{
      "scriptId":"u59"},
    "c5eba2554a144d0c8d2d3f3d65c25b5f":{
      "scriptId":"u60"},
    "a37ef8781f9741daad96e43b1470c59d":{
      "scriptId":"u61"},
    "1fa397f6443e4d9798fdb006cb59f203":{
      "scriptId":"u62"},
    "a4d12eff69ee47a484bd933422c538c8":{
      "scriptId":"u63"},
    "c2f271fd8c554569b2a7a6c4d19c7030":{
      "scriptId":"u64"},
    "efbec744081a4c88bbd76cacc94c48d7":{
      "scriptId":"u65"},
    "99ebc89ede9e45fc98a61550d97f3675":{
      "scriptId":"u66"}}});