$axure.loadCurrentPage({
  "url":"文档.html",
  "generationDate":new Date(1457071974717.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f2afa027a2404ac686561bbe666b9379",
    "type":"Axure:Page",
    "name":"文档",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"03dc4bbc28b9487fbbf32cf4289a15ea",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":20},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"5ce1b54d0932459e9216cd20e80e0b25",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4d860c65d30d413ca36362f4182bfc17",
                  "label":"",
                  "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":810,
                      "height":530}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"22ee14812f564517ad7348f478f6210f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":810,
                          "height":530}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/下载页/u1.png"}},
{
                  "id":"8162b9f1b8ed4dca91fcdc4c8b6075b3",
                  "label":"",
                  "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":810,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"349e5b8c3cd04789b70d0d8dbf707446",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":810,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"f5586f9a101743ffb4e780113a2d4586",
                  "label":"",
                  "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":5},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7d0ddccc674c49359fa142c036a3fddd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":5},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u5.png"}},
{
                  "id":"4dec274e4d2d4c5eb7087c84af509ca5",
                  "label":"",
                  "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":550,
                      "y":30},
                    "size":{
                      "width":30,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f987990fc0014a308d968c940643b779",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":550,
                          "y":30},
                        "size":{
                          "width":30,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"01eb9e94726b466aad31ee796f2e974a",
                  "label":"",
                  "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":627,
                      "y":31},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"04a1557d9b5a4785a28bacd1c7cf775f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":627,
                          "y":31},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 文档",
                              "target":{
                                "targetType":"page",
                                "url":"文档.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1e6147694de046d3acfd9c118fc6258c",
                  "label":"",
                  "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":701,
                      "y":31},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"942119d1a18f4a62b64537219cf3257b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":701,
                          "y":31},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 链接",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"125e6bf1a6d246718b770a5dc8b09a49",
                  "label":"",
                  "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":590,
                      "y":31},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3a1fc131d97b4ac4a9016ba2dc23c100",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":590,
                          "y":31},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 链接",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d26d0a9754434d35bdc4af3931a6dfe4",
                  "label":"",
                  "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":490},
                    "size":{
                      "width":810,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b7f831cad7ca4c3789616c770328b2ee",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":490},
                        "size":{
                          "width":810,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u136.png"}},
{
                  "id":"f31dd9e802b6477da9fee8ae203d350b",
                  "label":"",
                  "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":88,
                      "y":502},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7dfd32735029485da889774092a71424",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":88,
                          "y":502},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"05690d6985e343eaac58fb3c1fda06b5",
                  "label":"",
                  "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":140,
                      "y":502},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dbf71f8e9f9a4629830685671412158d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":140,
                          "y":502},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0924393c2e2d44b99c9b410563b8eb5c",
                  "label":"",
                  "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":216,
                      "y":502},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"85c7a9ae97aa4b73bdbbc830fc5f8d98",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":216,
                          "y":502},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5721337c043d40f49f17196af6e624ac",
                  "label":"",
                  "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":39,
                      "y":502},
                    "size":{
                      "width":29,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"20b9c8c92fcd44f88cd0d16f354028a5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":39,
                          "y":502},
                        "size":{
                          "width":29,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8013585fb9934dcaba929fd9b8d5da9e",
                  "label":"",
                  "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":279,
                      "y":502},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"64974a5ba2f845e693fdf581053ae82b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":279,
                          "y":502},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2df1651666a84a52985c7016b00f880e",
                  "label":"",
                  "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":664,
                      "y":31},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7106502d7ebf42e9889d22358e7c93a2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":664,
                          "y":31},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 文档",
                              "target":{
                                "targetType":"page",
                                "url":"文档.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"956b230fcbd04b12bd9a53a644cbb129",
                  "label":"",
                  "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":764,
                      "y":28},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8b6cbeda028644aa9232533a5c753ba5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"03dc4bbc28b9487fbbf32cf4289a15ea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":764,
                          "y":28},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u22.png"}}]}]},
{
          "id":"0731ad9a31cf42cdbb90e40e07803e07",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":100},
            "size":{
              "width":770,
              "height":400}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db849ef6b72d4306a130e4de966b4322",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":100},
                "size":{
                  "width":770,
                  "height":400}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文档/u31.png"}},
{
          "id":"2e6da1ddf5a34f0f8cd26a1e5f7da1b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":130},
            "size":{
              "width":120,
              "height":350}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d1167982a7449e5a3f9c54324df65da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":130},
                "size":{
                  "width":120,
                  "height":350}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文档/u33.png"}},
{
          "id":"f9d12f296a534bebbd4c630dc85ba01f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":130},
            "size":{
              "width":540,
              "height":340}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ff41507a6694822b7c252767e999c52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":130},
                "size":{
                  "width":540,
                  "height":340}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f81ccf95da5e4a92af21529ca7970c12",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":166},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"672140dfff2d429ea4151cc5d9de85d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":166},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ce4a0242adc4ea78784743c22be4c86",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":60,
              "y":140},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ac2e60771ec4c30ad76f0c44a008a57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":60,
                  "y":140},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de2742f69c7e4a0386f780a228ca81a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":192},
            "size":{
              "width":30,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72c0482eda394889b372bdbd6092e57e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":192},
                "size":{
                  "width":30,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47303194986049d0806f5569b8f3cf9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":218},
            "size":{
              "width":62,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44c1b3986f464bbea21d1ca39e1975e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":218},
                "size":{
                  "width":62,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e482ec8bc9884879a0ad76387e22e5b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":244},
            "size":{
              "width":88,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8e9ea4493ad4e028239d609d3f5b89f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":244},
                "size":{
                  "width":88,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a5d6bf2f9ef4e26ae4415c4d7d60c46",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":325},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d7e4463f0dcd4506b36bc53da974a0c3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":360},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9c8f96fb53244b9bbc2efb32b5a3ec82",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":416},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d71e415063814271bb595067d242a859",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":416},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a82e33da423b4cc9a6ebb3c698c8b31b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":434},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6510015771d044e8b69103c57bd71f8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":434},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3a45974863c48b09d04fb541a9e57da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":451},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3110e69c49a244788630f536229c81a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":451},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b362c4a774ce48e7a158591edc2bb31c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":60,
              "y":391},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cf32a4e5fd84d63b41333d08427d0cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":60,
                  "y":391},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48273bf112d34d379fe024bd3d020a9e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":115},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "03dc4bbc28b9487fbbf32cf4289a15ea":{
      "scriptId":"u0"},
    "4d860c65d30d413ca36362f4182bfc17":{
      "scriptId":"u1"},
    "22ee14812f564517ad7348f478f6210f":{
      "scriptId":"u2"},
    "8162b9f1b8ed4dca91fcdc4c8b6075b3":{
      "scriptId":"u3"},
    "349e5b8c3cd04789b70d0d8dbf707446":{
      "scriptId":"u4"},
    "f5586f9a101743ffb4e780113a2d4586":{
      "scriptId":"u5"},
    "7d0ddccc674c49359fa142c036a3fddd":{
      "scriptId":"u6"},
    "4dec274e4d2d4c5eb7087c84af509ca5":{
      "scriptId":"u7"},
    "f987990fc0014a308d968c940643b779":{
      "scriptId":"u8"},
    "01eb9e94726b466aad31ee796f2e974a":{
      "scriptId":"u9"},
    "04a1557d9b5a4785a28bacd1c7cf775f":{
      "scriptId":"u10"},
    "1e6147694de046d3acfd9c118fc6258c":{
      "scriptId":"u11"},
    "942119d1a18f4a62b64537219cf3257b":{
      "scriptId":"u12"},
    "125e6bf1a6d246718b770a5dc8b09a49":{
      "scriptId":"u13"},
    "3a1fc131d97b4ac4a9016ba2dc23c100":{
      "scriptId":"u14"},
    "d26d0a9754434d35bdc4af3931a6dfe4":{
      "scriptId":"u15"},
    "b7f831cad7ca4c3789616c770328b2ee":{
      "scriptId":"u16"},
    "f31dd9e802b6477da9fee8ae203d350b":{
      "scriptId":"u17"},
    "7dfd32735029485da889774092a71424":{
      "scriptId":"u18"},
    "05690d6985e343eaac58fb3c1fda06b5":{
      "scriptId":"u19"},
    "dbf71f8e9f9a4629830685671412158d":{
      "scriptId":"u20"},
    "0924393c2e2d44b99c9b410563b8eb5c":{
      "scriptId":"u21"},
    "85c7a9ae97aa4b73bdbbc830fc5f8d98":{
      "scriptId":"u22"},
    "5721337c043d40f49f17196af6e624ac":{
      "scriptId":"u23"},
    "20b9c8c92fcd44f88cd0d16f354028a5":{
      "scriptId":"u24"},
    "8013585fb9934dcaba929fd9b8d5da9e":{
      "scriptId":"u25"},
    "64974a5ba2f845e693fdf581053ae82b":{
      "scriptId":"u26"},
    "2df1651666a84a52985c7016b00f880e":{
      "scriptId":"u27"},
    "7106502d7ebf42e9889d22358e7c93a2":{
      "scriptId":"u28"},
    "956b230fcbd04b12bd9a53a644cbb129":{
      "scriptId":"u29"},
    "8b6cbeda028644aa9232533a5c753ba5":{
      "scriptId":"u30"},
    "0731ad9a31cf42cdbb90e40e07803e07":{
      "scriptId":"u31"},
    "db849ef6b72d4306a130e4de966b4322":{
      "scriptId":"u32"},
    "2e6da1ddf5a34f0f8cd26a1e5f7da1b5":{
      "scriptId":"u33"},
    "2d1167982a7449e5a3f9c54324df65da":{
      "scriptId":"u34"},
    "f9d12f296a534bebbd4c630dc85ba01f":{
      "scriptId":"u35"},
    "7ff41507a6694822b7c252767e999c52":{
      "scriptId":"u36"},
    "f81ccf95da5e4a92af21529ca7970c12":{
      "scriptId":"u37"},
    "672140dfff2d429ea4151cc5d9de85d1":{
      "scriptId":"u38"},
    "0ce4a0242adc4ea78784743c22be4c86":{
      "scriptId":"u39"},
    "2ac2e60771ec4c30ad76f0c44a008a57":{
      "scriptId":"u40"},
    "de2742f69c7e4a0386f780a228ca81a5":{
      "scriptId":"u41"},
    "72c0482eda394889b372bdbd6092e57e":{
      "scriptId":"u42"},
    "47303194986049d0806f5569b8f3cf9f":{
      "scriptId":"u43"},
    "44c1b3986f464bbea21d1ca39e1975e0":{
      "scriptId":"u44"},
    "e482ec8bc9884879a0ad76387e22e5b7":{
      "scriptId":"u45"},
    "e8e9ea4493ad4e028239d609d3f5b89f":{
      "scriptId":"u46"},
    "5a5d6bf2f9ef4e26ae4415c4d7d60c46":{
      "scriptId":"u47"},
    "d7e4463f0dcd4506b36bc53da974a0c3":{
      "scriptId":"u48"},
    "9c8f96fb53244b9bbc2efb32b5a3ec82":{
      "scriptId":"u49"},
    "d71e415063814271bb595067d242a859":{
      "scriptId":"u50"},
    "a82e33da423b4cc9a6ebb3c698c8b31b":{
      "scriptId":"u51"},
    "6510015771d044e8b69103c57bd71f8c":{
      "scriptId":"u52"},
    "e3a45974863c48b09d04fb541a9e57da":{
      "scriptId":"u53"},
    "3110e69c49a244788630f536229c81a6":{
      "scriptId":"u54"},
    "b362c4a774ce48e7a158591edc2bb31c":{
      "scriptId":"u55"},
    "5cf32a4e5fd84d63b41333d08427d0cb":{
      "scriptId":"u56"},
    "48273bf112d34d379fe024bd3d020a9e":{
      "scriptId":"u57"}}});